@startuml

title __GFX's Class Diagram__\n

  namespace GFXandEffects {
    class GFXandEffects.Assets {
        {static} + Ubuntu18 : Font
        {static} + Ubuntu28 : Font
        {static} + Ubuntu34 : Font
        {static} + Ubuntu40 : Font
        {static} + Ubuntu58 : Font
        {static} + Ubuntu76 : Font
        {static} + armor_b : BufferedImage[]
        {static} + armor_f : BufferedImage[]
        {static} + arrow : BufferedImage[]
        {static} + arrowV : BufferedImage
        {static} + bar_loaded : BufferedImage[]
        {static} + big_button_template : BufferedImage[]
        {static} + bow_lb : BufferedImage
        {static} + bow_lf : BufferedImage
        {static} + bow_rb : BufferedImage
        {static} + bow_rf : BufferedImage
        {static} + cloak_b : BufferedImage
        {static} + cloak_f : BufferedImage
        {static} + counter : BufferedImage[]
        {static} + cup : BufferedImage[]
        {static} + dynamicBackground : BufferedImage[]
        {static} + fire : BufferedImage[]
        {static} + icicle_b : BufferedImage
        {static} + icicle_f : BufferedImage
        {static} + loadingDot : BufferedImage[]
        {static} + logo : BufferedImage
        {static} + map : BufferedImage
        {static} + medium_button_template : BufferedImage[]
        {static} + medkit : BufferedImage
        {static} + onOff_button_template : BufferedImage[]
        {static} + pause_button : BufferedImage[]
        {static} + player : BufferedImage[]
        {static} + progressbar_b : BufferedImage
        {static} + progressbar_f : BufferedImage
        {static} + rollimg : BufferedImage[]
        {static} + shield : BufferedImage
        {static} + slider_back : BufferedImage
        {static} + slider_front : BufferedImage
        {static} + square : BufferedImage
        {static} + swan : BufferedImage
        {static} + switchB : BufferedImage[]
        {static} + sword : BufferedImage
        {static} + tile : BufferedImage[]
        {static} + timerFrame : BufferedImage
        {static} + wand : BufferedImage
        {static} - ARROW_HEIGHT : int
        {static} - ARROW_WIDTH : int
        {static} - P_HEIGHT : int
        {static} - P_WIDTH : int
        {static} - R_HEIGHT : int
        {static} - R_WIDTH : int
        {static} - TILE_HEIGHT : int
        {static} - TILE_WIDTH : int
        {static} + init()
        {static} + initLoadingScreen()
        {static} + loadImage()
        {static} + rotate()
    }
  }
  

  namespace GFXandEffects {
    class GFXandEffects.DynamicBackground {
        {static} - cluePoint : int[]
        - difference : double
        - dynamicBackground : BufferedImage[]
        - height : int
        - position : double[]
        - right : boolean[]
        - ticks : int
        - width : int
        + DynamicBackground()
        + render()
        + tick()
        - changeDirection()
        - moveBackgroundLogic()
    }
  }
  

  namespace GFXandEffects {
    class GFXandEffects.FontLoader {
        {static} + loadFont()
    }
  }
  

  namespace GFXandEffects {
    class GFXandEffects.SpriteSheet {
        - sheet : BufferedImage
        + SpriteSheet()
        + crop()
    }
  }
  

  namespace GFXandEffects {
    class GFXandEffects.Text {
        {static} + drawString()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
