@startuml

title __GIT_LUDO_LEGENDS_2.0's Class Diagram__\n

  namespace entities {
    class entities.Board {
    }
  }
  

  namespace entities {
    namespace Counters {
      class entities.counters.Albali {
      }
    }
  }
  

  namespace entities {
    namespace Counters {
      abstract class entities.counters.Counter {
      }
    }
  }
  

  namespace entities {
    namespace Counters {
      class entities.counters.Funi {
      }
    }
  }
  

  namespace entities {
    namespace Counters {
      class entities.counters.Intan {
      }
    }
  }
  

  namespace entities {
    namespace Counters {
      class entities.counters.Lich {
      }
    }
  }
  

  namespace entities {
    namespace Counters {
      class entities.counters.Mira {
      }
    }
  }
  

  namespace entities {
    namespace Counters {
      class entities.counters.Polaris {
      }
    }
  }
  

  namespace entities {
    namespace Counters {
      class entities.counters.Samaya {
      }
    }
  }
  

  namespace entities {
    namespace Counters {
      class entities.counters.Saph {
      }
    }
  }
  

  namespace entities {
    namespace Counters {
      class entities.counters.Venator {
      }
    }
  }
  

  namespace entities {
    abstract class entities.Entity {
    }
  }
  

  namespace entities {
    namespace HUD {
      class entities.HUD.BarParticle {
      }
    }
  }
  

  namespace entities {
    namespace HUD {
      class entities.HUD.Dice {
      }
    }
  }
  

  namespace entities {
    namespace HUD {
      class entities.HUD.Timer {
      }
    }
  }
  

  namespace entities {
    namespace HUD {
      class entities.HUD.UltimateBar {
      }
    }
  }
  

  namespace entities {
    class players.PositionOnMap {
    }
  }
  

  namespace entities {
    namespace ui {
      class entities.ui.Button {
      }
    }
  }
  

  namespace entities {
    namespace ui {
      class entities.ui.CounterTile {
      }
    }
  }
  

  namespace entities {
    namespace ui {
      class entities.ui.LegendPick {
      }
    }
  }
  

  namespace entities {
    namespace ui {
      class entities.ui.Pause {
      }
    }
  }
  

  namespace entities {
    namespace ui {
      class entities.ui.PlayerPick {
      }
    }
  }
  

  namespace entities {
    namespace ui {
      class entities.ui.Slider {
      }
    }
  }
  

  namespace entities {
    namespace ui {
      class entities.ui.Switch {
      }
    }
  }
  

  namespace entities {
    namespace ui {
      class entities.ui.TextField {
      }
    }
  }
  

  namespace entities {
    namespace ui {
      class entities.ui.Tile {
      }
    }
  }
  

  namespace GFXandEffects {
    class GFXandEffects.Assets {
    }
  }
  

  namespace GFXandEffects {
    class GFXandEffects.DynamicBackground {
    }
  }
  

  namespace GFXandEffects {
    class GFXandEffects.FontLoader {
    }
  }
  

  namespace GFXandEffects {
    class GFXandEffects.SpriteSheet {
    }
  }
  

  namespace GFXandEffects {
    class GFXandEffects.Text {
    }
  }
  

  namespace players {
    class players.Blank {
    }
  }
  

  namespace players {
    class players.Bot {
    }
  }
  

  namespace players {
    class players.Person {
    }
  }
  

  namespace players {
    abstract class players.Player {
    }
  }
  

  namespace players {
    class players.PlayerData {
    }
  }
  

  namespace display {
    class display.Display {
    }
  }
  

  namespace input {
    class input.KeyboardManager {
    }
  }
  

  namespace input {
    class input.MouseManager {
    }
  }
  

  namespace ludogame {
    class ludogame.DBConnect {
    }
  }
  

  namespace ludogame {
    class ludogame.Game {
    }
  }
  

  namespace ludogame {
    class ludogame.Handler {
    }
  }
  

  namespace ludogame {
    class ludogame.Launcher {
    }
  }
  

  namespace ludogame {
    class ludogame.LoadingScreen {
    }
  }
  

  namespace states {
    class states.GameOverScreen {
    }
  }
  

  namespace states {
    class states.GameState {
    }
  }
  

  namespace states {
    class states.HighScoresState {
    }
  }
  

  namespace states {
    class states.MenuState {
    }
  }
  

  namespace states {
    class states.PrepState {
    }
  }
  

  namespace states {
    class states.SettingState {
    }
  }
  

  namespace states {
    abstract class states.State {
    }
  }
  

  entities.Board -up-|> entities.Entity
  entities.counters.Albali -up-|> entities.counters.Counter
  entities.counters.Counter -up-|> entities.Entity
  entities.counters.Counter o-- players.PositionOnMap : pos
  entities.counters.Counter o-- entities.HUD.UltimateBar : ultimateBar
  entities.counters.Counter o-- players.PositionOnMap : bufferedPosition
  entities.counters.Funi -up-|> entities.counters.Counter
  entities.counters.Intan -up-|> entities.counters.Counter
  entities.counters.Lich -up-|> entities.counters.Counter
  entities.counters.Mira -up-|> entities.counters.Counter
  entities.counters.Polaris -up-|> entities.counters.Counter
  entities.counters.Samaya -up-|> entities.counters.Counter
  entities.counters.Saph -up-|> entities.counters.Counter
  entities.counters.Venator -up-|> entities.counters.Counter
  entities.Entity o-- ludogame.Handler : handler
  entities.HUD.BarParticle -up-|> entities.Entity
  entities.HUD.Dice -up-|> entities.Entity
  entities.HUD.Timer -up-|> entities.Entity
  entities.HUD.UltimateBar -up-|> entities.Entity
  entities.HUD.UltimateBar o-- entities.counters.Counter : counter
  entities.ui.Button -up-|> entities.Entity
  entities.ui.CounterTile -up-|> entities.Entity
  entities.ui.LegendPick -up-|> entities.Entity
  entities.ui.Pause -up-|> entities.Entity
  entities.ui.Pause o-- ludogame.Handler : handler
  entities.ui.Pause o-- entities.ui.Button : menu
  entities.ui.PlayerPick -up-|> entities.Entity
  entities.ui.Slider -up-|> entities.Entity
  entities.ui.Slider o-- entities.ui.Button : reset
  entities.ui.Switch -up-|> entities.Entity
  entities.ui.TextField -up-|> entities.Entity
  entities.ui.Tile o-- ludogame.Handler : handler
  players.Blank -up-|> players.Player
  players.Bot -up-|> players.Player
  players.Person -up-|> players.Player
  players.Player o-- players.PositionOnMap : endingPos
  players.Player o-- ludogame.Handler : handler
  players.Player o-- players.PositionOnMap : startingPos
  input.KeyboardManager .up.|> java.awt.event.KeyListener
  input.MouseManager .up.|> java.awt.event.MouseListener
  input.MouseManager .up.|> java.awt.event.MouseMotionListener
  ludogame.Game .up.|> java.lang.Runnable
  ludogame.Game o-- states.State : gameState
  ludogame.Game o-- states.State : highScoresState
  ludogame.Game o-- states.State : menuState
  ludogame.Game o-- states.State : prepState
  ludogame.Game o-- states.State : settingState
  ludogame.Game o-- display.Display : display
  ludogame.Game o-- ludogame.Handler : handler
  ludogame.Game o-- input.KeyboardManager : keyboardManager
  ludogame.Game o-- input.MouseManager : mouseManager
  ludogame.Handler o-- display.Display : display
  ludogame.Handler o-- ludogame.Game : game
  ludogame.Handler o-- states.GameState : gameState
  ludogame.Handler o-- ludogame.LoadingScreen : loadingScreen
  ludogame.LoadingScreen .up.|> java.lang.Runnable
  ludogame.LoadingScreen o-- display.Display : display
  ludogame.LoadingScreen o-- ludogame.Handler : handler
  states.GameOverScreen o-- ludogame.Handler : handler
  states.GameOverScreen o-- entities.ui.Button : menu
  states.GameState -up-|> states.State
  states.GameState o-- entities.Board : board
  states.GameState o-- entities.HUD.Dice : dice
  states.GameState o-- states.GameOverScreen : gameOverScreen
  states.GameState o-- entities.ui.Pause : pause
  states.GameState o-- entities.HUD.Timer : timer
  states.HighScoresState -up-|> states.State
  states.HighScoresState o-- entities.ui.Button : back
  states.HighScoresState o-- ludogame.DBConnect : connect
  states.HighScoresState o-- GFXandEffects.DynamicBackground : dynamicBackground
  states.MenuState -up-|> states.State
  states.MenuState o-- GFXandEffects.DynamicBackground : dynamicBackground
  states.MenuState o-- entities.ui.Button : exit
  states.MenuState o-- entities.ui.Button : game
  states.MenuState o-- entities.ui.Button : ranking
  states.MenuState o-- entities.ui.Button : settings
  states.PrepState -up-|> states.State
  states.PrepState o-- GFXandEffects.DynamicBackground : dynamicBackground
  states.PrepState o-- entities.ui.Button : apply
  states.PrepState o-- entities.ui.Pause : pause
  states.SettingState -up-|> states.State
  states.SettingState o-- entities.ui.Button : apply
  states.SettingState o-- entities.ui.Button : back
  states.SettingState o-- entities.ui.Slider : buttonSize
  states.SettingState o-- entities.ui.Button : defaults
  states.SettingState o-- entities.ui.Slider : diceAnimTime
  states.SettingState o-- GFXandEffects.DynamicBackground : dynamicBackground
  states.SettingState o-- entities.ui.Switch : dynamicBackgroundSwitch
  states.SettingState o-- entities.ui.Switch : fpsCounterSwitch
  states.SettingState o-- entities.ui.Slider : sliderFps
  states.SettingState o-- entities.ui.Slider : ultLoad
  states.State o-- ludogame.Handler : handler


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
